### ISSUE TITLE
Values symbol

### ISSUE THREAD

**Issue by imevro** [css-modules/postcss-icss-values#4]
I think, better and safe use values with prefix symbol. For example, `$primary` like Sass or `@primary` like Less.

For example, I have value `gray`, which contains `#eee` as value, but `background-color: gray` processed as `background-color: gray` which is `#d3d3d` obviously.

**Comment by geelen** [comment]
I'd like to make this possible, and in fact the underlying replacement code will handle symbols of this type: https://github.com/css-modules/icss-replace-symbols/commit/9be290eb3c0f41c8b1ab24333099b412b4479119

The problem is being able to escape non-CSS-safe chars in ICSS, so it's not a small thing I'm afraid. You can already use variables like `--gray` if you prefer, I'll add a test case to demonstrate.
